image: golang:1.18.3-alpine

stages:
    - test

.bootstrap_script:
    before_script:
        - go install -mod vendor github.com/go-task/task/v3/cmd/task
        - go generate -tags tools tools/tools.go
        - task bootstrap

#
# Test
#
build:
    stage: test
    extends: .bootstrap_script
    script:
        - task build
        - ls -R bin

test:
    stage: test
    extends: .bootstrap_script
    script:
        - task test
