image: golang:1.18.3-alpine

stages:
    - test

.bootstrap_script:
    before_script:
        - apk add --update gcc libc-dev git
        - go install -mod vendor github.com/go-task/task/v3/cmd/task
        - go generate -tags tools tools/tools.go
        - task bootstrap

#
# Test
#
test:
    stage: test
    extends: .bootstrap_script
    script:
        - task test
        - task build
        - ls -R bin
#
# Build
#
# release:
#     image: docker:19.03.1
#     stage: build
#     only:
#         - tags
#     services:
#         - name: docker:19.03.1-dind
#           command: ["--experimental"]
#     before_script:
#         - apk update && apk add bash && apk add git
#         - git clone --recurse-submodules https://gitlab.com/music-library/release.git
#         - cd release
#         - git submodule update --remote backend
#         - git submodule update --remote client
#     script:
#         - docker login -u "$DOCKER_USER" -p "$DOCKER_TOKEN"
#         - docker build -t hmerritt/music-library-player:$CI_COMMIT_TAG -t hmerritt/music-library-player:latest .
#         - docker push hmerritt/music-library-player:latest
#         - docker push hmerritt/music-library-player:$CI_COMMIT_TAG
#     after_script:
#         - docker logout
